### ISSUE TITLE
Configuration values being ignored?

### ISSUE THREAD

**Issue by tstirrat15** [i18next/i18next-scanner#100]
See title.
#### Version
- i18next: <i>11.6.0</i>
- i18next-scanner: <i>2.6.5</i>

#### Configuration
```js
module.exports = {
  debug: true,
  removeUnusedKeys: true,
  lngs: ['en', 'ru'],
  ns: 'common',
  defaultLng: 'en',
  defaultValue: '__NOT_TRANSLATED__',
  resource: {
    loadPath: 'src/translations/{{lng}}/{{ns}}.json',
    savePath: 'src/translations/{{lng}}/{{ns}}.json',
  },
};
```
The red flag for me is `debug`. Here's the output when I run `yarn run i18next-scanner --config tools/i18next-scanner.config.js 'src/**/*.js'`:
```bash
➜  project git:(branch) ✗ yarn run i18next-scanner --config tools/i18next-scanner.config.js 'src/**/*.js'
yarn run v1.9.4
$ /home/me/project/node_modules/.bin/i18next-scanner --config tools/i18next-scanner.config.js 'src/**/*.js'
Done in 0.64s.
```
The `savePath` seems to be similarly ignored, and if the process is erroring out, it gives no indication of this, despite the output translation files being empty. Any ideas?

**Comment by tstirrat15** [comment]
I've verified that the configuration file is being read, because I put a `console.log("this file is being read")` at the top of the file, and that was output to the command line when I ran the command.

**Comment by daliusd** [comment]
Your configuration file is bad. All settings should be under "options".

**Comment by tstirrat15** [comment]
Ah. Thank you.
