### ISSUE TITLE
The scanner does not detect translations keys passed as params

### ISSUE THREAD

**Issue by djemalmohamed** [i18next/i18next-scanner#115]
Hello,

When passing translations keys as params to the i18next.t translation functions, the scanner does not detect those translations.

Example:
const menuItems = [
  {
    label: 'item1Key',
  },
  {
    label: 'item2Key',
  },
  {
    label: 'item3Key',
  },
];
and then :
{menuItems.map(menuItem => (
                {translate(menuItem.label)}
            ))}

The output scanned translation file does not contain item1Key, item2Key...

Thanks.

**Comment by daliusd** [comment]
You are expecting too much from scanner IMHO. As well, as developer I find this translation style completely wrong. ```t``` function should be used directly in menuItems array, like:

```
const menuItems = [
{
label: t('item1Key'),
},
```

I don't like the way you have implemented because that's hiding that 'item1Key' is localized.

**Comment by djemalmohamed** [comment]
Okay, convinced.
Thanks
