### ISSUE TITLE
Please support custom languages

### ISSUE THREAD

**Issue by p4ul** [i18next/i18next-scanner#116]
Hi,
The latest version 2.9.0 has broken some functionality for us. We have several standard languages
es-US, en-US etc but we also have 2 special languages "fixed" and "random"

- random: replaces each word with a random word
- fixed: replaces each string with the repeated character pattern "EM" that match the length of string

We find random is good for usability testing, can people use the site in a foreign language etc.
Fixed is good for locating missing translations.

Would it please be possible to replace this return false with a default (or empty) plural object but leave the warning in there that it is a non-standard language?
https://github.com/i18next/i18next-scanner/blob/4406fd1e26c01530f7214366e2832c9ee049868e/src/parser.js#L257

Cheers!

**Comment by cheton** [comment]
Thank you for reporting this issue. It's fixed in v2.9.1.
