### ISSUE TITLE
Avoid parsing commented out code

### ISSUE THREAD

**Issue by msurdi** [i18next/i18next-scanner#118]
#### Version
- i18next: <i>11.9.1</i>
- i18next-scanner: <i>2.9.1</i>

#### Configuration
```js
{
        removeUnusedKeys: true,
        sort: true,
        nsSeparator: false,
        keySeparator: false,
        func: {
            list: ['gettext', 'lazyGettext'],
        },
        defaultValue: (lng, ns, key) => key,
        lngs: ['en'],
        resource: {
            loadPath: 'messages.json',
            savePath: 'messages.json',
        },
    }
```

Is there any way to avoid extracting strings from commented out code? Given the previous configuration, if I have a JavaScript File with:

```js
/*
* gettext('skip this')
*/
```

I want it to not be extracted to messages.json.

**Comment by daliusd** [comment]
func extraction is regexp based in i18next-scanner so it can not differentiate between commented and not commented out code. This is quite big feature request IMHO.

**Comment by cheton** [comment]
If you're using the streaming API, you can use [gulp-decomment](https://github.com/vitaly-t/gulp-decomment) to remove comments from code:

```js
const scanner = require('i18next-scanner');
const vfs = require('vinyl-fs');
const sort = require('gulp-sort');
const decomment = require('gulp-decomment');
const options = {
    // See options at https://github.com/i18next/i18next-scanner#options
};
vfs.src(['/path/to/src'])
    .pipe(sort()) // Sort files in stream by path
    .pipe(decomment()) // Remove comments
    .pipe(scanner(options))
    .pipe(vfs.dest('/path/to/dest'));
```

Integrate decomment to the [cli tool](https://github.com/i18next/i18next-scanner/blob/master/bin/cli.js#L55-L58) is not hard. I will try to find a proper way for passing decomment options.

**Comment by gong9** [comment]
> func 提取是基于 i18next-scanner 的正则表达式，因此它无法区分已注释和未注释的代码。这是一个相当大的功能请求恕我直言。

Why not use regular expressions to distinguish?
