### ISSUE TITLE
Translation keys in json object format?

### ISSUE THREAD

**Issue by vegetablesalad** [i18next/i18next-scanner#119]
My translations are configured as object:

```
{
  "weatherReport": {
    "title": "Weather",
    "currentlyIn": "Currently in",
    "WaterTemperature": "Water temperature",
    "WaterLevel": "Water level"
  }
}
```
but *i18next-scanner* want's to read and write them as 
```
{
  "weatherReport.title": "__STRING_NOT_TRANSLATED__",
  "weatherReport.currentlyIn": "__STRING_NOT_TRANSLATED__",
  "weatherReport.WaterTemperature": "__STRING_NOT_TRANSLATED__",
  "weatherReport.WaterLevel": "__STRING_NOT_TRANSLATED__",
  "weatherReport.InformationLastUpdatedAt": "__STRING_NOT_TRANSLATED__",
}
```

Can I configure this library to use this format?

**Comment by daliusd** [comment]
Have you changed keySeparator in your configuration?

**Comment by vegetablesalad** [comment]
@daliusd I tried to set it to *true* or *false* and nothing seemed to change.

**Comment by vegetablesalad** [comment]
@daliusd I thought that *keySeparator* manages with what character it separates my key.
> Type: String or false Default: '.'
I tried *true* / *false* / *-* and nothing changed. I couldn't even get it to use *[-]* instead of *[.]*

**Comment by vegetablesalad** [comment]
Thank you, I changed both of them to "." and it worked!

**Comment by sibelius** [comment]
@vegetablesalad what was the final config?

**Comment by vegetablesalad** [comment]
@sibelius I'll just post the entire file as it is:
`let fs = require('fs');
let chalk = require('chalk');

module.exports = {
    options: {
        debug: true,
        func: {
            list: ['i18next.t', 'i18n.t'],
            extensions: ['.js', '.jsx']
        },
        trans: {
            component: 'Trans',
            i18nKey: 'i18nKey',
            defaultsKey: 'defaults',
            extensions: ['.js', '.jsx'],
            fallbackKey: function(ns, value) {
                // Returns a hash value as the fallback key
                return sha1(value);
            }
        },
        lngs: ['en'],
        ns: [
            'locale',
            'resource'
        ],
        defaultLng: 'en',
        defaultNs: 'resource',
        defaultValue: '',
        resource: {
            loadPath: 'config/jsons/lang/{{lng}}.json',
            savePath: 'config/jsons/lang/{{lng}}.json',
            jsonIndent: 2,
            lineEnding: '\n'
        },
        nsSeparator: ":", // namespace separator
        keySeparator: ".", // key separator
        interpolation: {
            prefix: '{{',
            suffix: '}}'
        }
    },
    transform: function customTransform(file, enc, done) {
        "use strict";
        const parser = this.parser;
        const content = fs.readFileSync(file.path, enc);
        let count = 0;

        parser.parseFuncFromString(content, { list: ['__'] }, (key, options) => {
            parser.set(key, Object.assign({}, options, {
                nsSeparator: ":",
                keySeparator: "."
            }));
            ++count;
        });

       

        done();
    }
};
`
