### ISSUE TITLE
White space handling

### ISSUE THREAD

**Issue by lmaillet** [i18next/i18next-scanner#126]
#### Version
- i18next: <i>^9.0.0</i>
- i18next-scanner: <i>2.9.1</i>

Hi,

I've got a problem with white space handling when parsing my files.
```jsx
<Trans i18nKey="HELLO_WORLD">
		Hello <b>world</b>
</Trans>
```
Will result on `HELLO_WORLD: Hello <1>world</1>;`. That was expected.

But
```jsx
<Trans i18nKey="HELLO_WORLD">
		Hello
		<b>world</b>
</Trans>
```
Will result on `HELLO_WORLD: Hello<1>world</1>;` without any white space after Hello.

Looks like when there is a tag after a line break, the needed white space is omitted.

Help is welcome !

**Comment by lmaillet** [comment]
Changing the current unit tests of the project from 
```jsx
<Trans i18nKey="components">
    Go to
    <Anchor href="/administration/tools">Administration > Tools</Anchor>
    to download administrative tools.
</Trans>
```
To
```jsx
<Trans i18nKey="components">
    Go to <Anchor href="/administration/tools">Administration > Tools</Anchor> to download administrative tools.
</Trans>
```

Will result in 
![image](https://user-images.githubusercontent.com/35027619/51735507-e7044000-2087-11e9-975a-e575769d327f.png)

Could someone have a look ?

**Comment by daliusd** [comment]
JSX is not HTML. Newline does not produce space. Your code should look like this.
```
<Trans i18nKey="HELLO_WORLD">
		Hello{' '}
		<b>world</b>
</Trans>
```

I'm pretty sure that if you have written your code like you did in JSX then you should have problem not only in Trans element.

**Comment by lmaillet** [comment]
Thanks for your help.
It make sense, I will had {' '} :smiley:
