### ISSUE TITLE
parseFuncFromString

### ISSUE THREAD

**Issue by sm2017** [i18next/i18next-scanner#127]
I have a function like `intl.formatMessage({id:'lang.id'})` , How can I scan it? as the argument is object the scanner skip it

**Comment by sm2017** [comment]
@cheton can you help me?

**Comment by sm2017** [comment]
Still waiting for reply!!

**Comment by daliusd** [comment]
As much as I'm familiar with i18next-scanner code what you want is not possible without rewrite of the code.

Honestly, it is not clear what you want to achieve. Why argument is object and not string? What result do you expect in resulting files? Could you point to i18next documentation that shows that i18next supports this?

**Comment by sm2017** [comment]
@daliusd I love i18next and always I use it in my projects
Now I am working in a project , has https://github.com/yahoo/react-intl but lack of scanner
I have two form of traslate function , one is string as parameter second is `intl.formatMessage({id:'lang.id'})`

**Comment by daliusd** [comment]
i18next-scanner in that case is wrong product to use.

Check out https://github.com/akameco/extract-react-intl-messages

**Comment by sm2017** [comment]
@daliusd thanks , But I tried it before and not works as I expect
Thank you very much
