### ISSUE TITLE
Unable to parse Trans component with the content

### ISSUE THREAD

**Issue by sm2017** [i18next/i18next-scanner#130]
I am using i18next for react-native@0.58.3
i18next cannot parse Trans component , I see similar topics but not helped me

#### Version
- i18next: <i>14.0.1</i>
- i18next-scanner: <i>2.9.1</i>

#### Configuration
```js
module.exports = {
  options: {
    debug: true,
    removeUnusedKeys: true,
    sort: true,
    func: {
      list: [
        't',
      ],
      extensions: [
        '.js',
        '.jsx',
      ],
    },
    trans: {
      component: 'Trans',
      i18nKey: 'i18nKey',
      defaultsKey: 'defaults',
      extensions: [
        '.js',
        '.jsx',
      ],
      fallbackKey: function(ns, value) {
        return value;
      },
    },
    lngs: [
      'en-US',
      'en-GB',
    ],
    ns: [
      'translation',
    ],
    defaultLng: 'en-US',
    defaultNs: 'translation',
    defaultValue(lng, ns, key) {
      return key;
    },
    resource: {
      loadPath: 'src/locales/{{lng}}/{{ns}}.json',
      savePath: 'src/locales/{{lng}}/{{ns}}.json',
      jsonIndent: 2,
      lineEnding: '\n',
    },
    nsSeparator: false,
    keySeparator: false,
    interpolation: {
      prefix: '{{',
      suffix: '}}',
    },
  },
};

```

**Comment by sm2017** [comment]
@cheton reply please

**Comment by daliusd** [comment]
You should give more details what is not working for you. Do you get error? Is parsing result wrong?

**Comment by sm2017** [comment]
@daliusd To reproduce it 

create `src/Test.js`

```js
import React, {Component} from 'react';
import {Trans, withNamespaces} from "react-i18next";

type Props = {};

type State = {};

class Test extends Component<Props, State> {
  render() {
    return (
      <Trans i18nKey="myTest">
        Test Trans
      </Trans>
    );
  }
}

export default  withNamespaces()(Test);
```

When I run `i18next-scanner --config i18next-scanner-config.js 'src/**/*.{js,jsx}'` error is 

```bash
i18next-scanner: Unable to parse Trans component with the content
{ SyntaxError: Unexpected token (5:5)
    at Object.pp$4.raise (C:\test\node_modules\acorn\dist\acorn.js:2807:13)
    at Object.pp.unexpected (C:\test\node_modules\acorn\dist\acorn.js:688:8)
    at Object.pp.semicolon (C:\test\node_modules\acorn\dist\acorn.js:665:64)
    at Object.pp$1.parseExpressionStatement (C:\test\node_modules\acorn\dist\acorn.js:1141:8)
    at Object.pp$1.parseStatement (C:\test\node_modules\acorn\dist\acorn.js:869:24)
    at Object.parseStatement (C:\test\node_modules\acorn-dynamic-import\lib\index.js:63:118)
    at Object.parseStatement (C:\test\node_modules\acorn-import-meta\index.js:38:22)
    at Object.pp$1.parseTopLevel (C:\test\node_modules\acorn\dist\acorn.js:747:23)
    at Object.parse (C:\test\node_modules\acorn\dist\acorn.js:550:15)
    at Function.parse (C:\test\node_modules\acorn\dist\acorn.js:573:35) pos: 140, loc: Position { line: 5, column: 5 }, raisedAt: 145 }
import React, {Component} from 'react';
import {Text, View} from 'react-native';
import {Trans, withNamespaces} from "react-i18next";

type Props = {};

type State = {};

class Test extends Component<Props, State> {
  render() {
    return (
      <Trans i18nKey="myTest">
        Test Trans
      </Trans>
    );
  }
}

export default  withNamespaces()(Test);
```

**Comment by daliusd** [comment]
So error shows that you have error in line 5, where you have "type State...". This is not javascript, this is typescript (or maybe flow). That means you should transpile your code first. Check this issue for ideas what to do https://github.com/i18next/i18next-scanner/issues/128.

**Comment by sm2017** [comment]
@daliusd I add `transform` to conflig

```js
  transform: function customTransform(file, enc, done) {
    const parser = this.parser;

    const options = {
      presets: ['@babel/preset-flow'],
    };

    const code = require('@babel/core').transformFile(file.path, options);
    parser.parseTransFromString(code);
    done();
  },
```

but not solved , I tried `@babel/preset-typescript` too , Can you show me how can I `transform` code?

**Comment by daliusd** [comment]
First, why are you trying typescript or flow? I think you should know what language you write your program in. If you don't know then I don't know either and can't solve your problem. If you writing in pure javascript remove type lines.

**Comment by sm2017** [comment]
I don't use typescript, I am writing in pure JavaScript + flow 

I follow flow syntax , https://flow.org/en/docs/react/components/

Like 

```js

import * as React from 'react';

type Props = {
  foo: number,
  bar?: string,
};

class MyComponent extends React.Component<Props> {
  render() {
    this.props.doesNotExist; // Error! You did not define a `doesNotExist` prop.

    return <div>{this.props.bar}</div>;
  }
}

<MyComponent foo={42} />;

```

My codes works well, I have problem with i18next scanner

**Comment by daliusd** [comment]
In that case \@babel/preset-flow most probably is good choice. However I believe transform function expects content, not file. Read content like this const content = fs.readFileSync(file.path, enc); . As well you can add some console.log statements to your customTransform function to debug out all possible problems.

**Comment by sm2017** [comment]
I test both `transformFile` and `transform`+`readFileSync`

In both, I got Unable to parse Trans component with the content  error , in error I can see my codes too

**Comment by daliusd** [comment]
So after flow-preset transformation you must get different error than "SyntaxError: Unexpected token (5:5)". What error do you get?

**Comment by sm2017** [comment]
Unfortunately , there is no different

Can you please try above mentioned example + configuration + transform

**Comment by daliusd** [comment]
You are missing at least jsx syntax plugin. Without it babel does not understand jsx files.

You can use babel client (`npm i \@babel/cli`) to test if your configuration transpiles file properly: 
babel --plugins @babel/plugin-syntax-jsx --presets @babel/preset-flow src/Test.js

And again simple `console.log` in customTransform function helps to identify bugs in your code. Here is version that should work for you. Of course don't forget install \@babel packages that are used.

```
transform: function customTransform(file, enc, done) {
        "use strict";
        const parser = this.parser;

        const options = {
            presets: ['@babel/preset-flow'],
            plugins: ['@babel/plugin-syntax-jsx'],
        };
        const content = fs.readFileSync(file.path, enc);

        const code = require('@babel/core').transform(content, options);
        parser.parseTransFromString(code.code);
        done();
    }
```

**Comment by sm2017** [comment]
@daliusd I cannot understand why your transform don't works , I see `console.log(code.code)` , and it is transformed nicely but the error `Unable to parse Trans component with the content` shown with not transformed code

To reproduce issue

```bash
git clone https://github.com/sm2017/scanner-issue.git
cd scanner-issue
yarn install
yarn run i18next-scanner
```


I create `i18next-scanner` script https://github.com/sm2017/scanner-issue/blob/master/package.json#L8
You can see babel dependencies https://github.com/sm2017/scanner-issue/blob/master/package.json#L16-L18 are installed

config is same as we discuss in the  issue https://github.com/sm2017/scanner-issue/blob/master/i18next-scanner.config.js

**Comment by daliusd** [comment]
@sm2017 There are 1.5 problem in your code. First you parse for Trans twice. First time, default parsing (this will report error), second time custom parsing but you have problem with custom parsing.

You can disable default error with:
```
    trans: {
            component: 'Trans',
            extensions: [],
        },
```

Now custom parsing will still not work. If you will write `console.log(code)` you will see that bunch of plugins are used. `console.log(code.code)` will show that your code is transformed slightly too much and you have lost jsx. Because of that i18next-scanner will not be able to parse strings from Trans components because there is no Trans component anymore in jsx form. You can delete `babel.config.js` and problem with too many plugins will go away. I will leave it for you to figure out how to make it work with babel.config.js - I mean how to ignore babel.config.js in customTransform function.

**Comment by sm2017** [comment]
@daliusd Thank you very much
