### ISSUE TITLE
Extracting namespace from Trans component

### ISSUE THREAD

**Issue by char0n** [i18next/i18next-scanner#137]
Hi,

I could not find a way to hot extract `Trans` component into appropriate namespace file without uing `i18nKey` prop explicitly. `Trans` component has a `ns` prop, but that is not being read at all. Important thing to note is that I'm not using surrogate keys, I'm using autogenerated keys.

```jsx
      <Trans count={count} ns="feature1">
        Hello <strong>World</strong>, you have {{count}} unread message.
      </Trans>
```

This translation is going to be exported into `translation.json` file, instead of `feature1.json` file. The only way I can make this translation go into proper file is by using `i18nKey` prop.
```jsx
      <Trans i18nKey="feature1:message_id" count={count} ns="feature1">
        Hello <strong>World</strong>, you have {{count}} unread message.
      </Trans>
```
Am I missing something ? I there a way to achieve what I want or the support for this is not available at all ?

Thank you

#### Version
- i18next: <i>15.0.6</i>
- i18next-scanner: <i>2.10.0</i>

#### Configuration
```js
'use strict';


module.exports = {
  input: [
    'src/**/*.{js,jsx}',
    // Use ! to filter out files or directories
    '!src/i18n/**',
    '!src/locales',
    '!**/node_modules/**',
  ],
  output: 'src/locales',
  options: {
    debug: true,
    removeUnusedKeys: false,
    sort: false,
    attr: {
      list: ['data-i18n'],
      extensions: ['.html', '.htm']
    },
    func: {
      list: ['_', '__'],
      extensions: ['.js', '.jsx']
    },
    trans: {
      component: 'Trans',
      i18nKey: 'i18nKey',
      defaultsKey: 'defaults',
      extensions: ['.js', '.jsx'],
      fallbackKey: (ns, value) => value,
    },
    lngs: ['en'],
    ns: ['feature1', 'translation'],
    defaultLng: 'en',
    defaultNs: 'translation',
    defaultValue: (lng, ns, key) => {
      if (lng === 'en') {
        return key;
      }
      return '__NOT_TRANSLATED__';
    },
    resource: {
      loadPath: '{{lng}}/{{ns}}.json',
      savePath: '{{lng}}/{{ns}}.json',
      jsonIndent: 2,
      lineEnding: '\n'
    },
    nsSeparator: ':',
    keySeparator: '.',
    pluralSeparator: '_',
    contextSeparator: '_',
    interpolation: {
      prefix: '{{',
      suffix: '}}'
    }
  },
};
```

**Comment by cheton** [comment]
I just walked through react-i18next documentation and source code, the `ns` prop is not explicitly documented in https://react.i18next.com/latest/trans-component#trans-props, but it is available in Trans.js:

```js
export function Trans({
  children,
  count,
  parent,
  i18nKey,
  tOptions,
  values,
  defaults,
  components,
  ns,
  i18n: i18nFromProps,
  t: tFromProps,
  ...additionalProps
}) {
```

It's a missing implementation in i18next-scanner, I can fix it a couple more days, but not today.
You create a pull request for review if it's quite urgent.

**Comment by cheton** [comment]
Fixed in [2.10.1](https://github.com/i18next/i18next-scanner/releases/tag/v2.10.1)

**Comment by char0n** [comment]
Thanks a lot. Testing it now.

**Comment by char0n** [comment]
Confirmed, the code is working, but we have another issue with trans component documented here: https://github.com/i18next/i18next-scanner/issues/125#issuecomment-473919033
