### ISSUE TITLE
SyntaxError: Unexpected token with simple React/JSX component

### ISSUE THREAD

**Issue by misto** [i18next/i18next-scanner#138]
I'm a bit embarrassed having to open this issue here, but I've been stuck for a few hours. I have a trivial React component

```
import React from "react"
import { Trans } from "react-i18next"

export default function() {
  return (
    <div>
      <Trans i18nKey="key" />
    </div>
  )
}
```

and the latest versions of i18next and i18next-scanner. But all I get is 

```
i18next-scanner: Unable to parse Trans component from "XXX/src/routes/Home/Component.js"
    SyntaxError: Unexpected token (7:20)
```

Any ideas what I might be doing wrong?

#### Version
- i18next: <i>15.0.7</i>
- i18next-scanner: <i>2.10.0</i>

#### Configuration
```js
{
  input: [
    "src/routes/Home/Component.js",
  ],
  output: "./",
  options: {
    debug: true,
    func: {
      list: ["t"],
      extensions: [".js"],
    },
    trans: {
      component: "Trans",
      i18nKey: "i18nKey",
      extensions: [".js"],
    },
    lngs: ["en", "de"],
    ns: ["translations"],
    defaultLng: "de",
    defaultNs: "translations",
    defaultValue: "__STRING_NOT_TRANSLATED__",
    resource: {
      loadPath: "src/i18n/{{lng}}/{{ns}}.json",
      savePath: "src/i18n/{{lng}}/{{ns}}.json",
      jsonIndent: 2,
      lineEnding: "\n",
    },
    keySeparator: ".",
  },
}
```

**Comment by misto** [comment]
Being a bit desperate, I removed my node_modules and did a new npm install and now I'm getting a new error:
```
i18next-scanner: Unable to parse Trans component from "XXX/src/routes/Home/Component.js"
    Error: acorn-private-class-elements does not support mixing different acorn copies
```

**Comment by cheton** [comment]
Can you show the code snippet of your Component.js that can produce the error? Thank you.

**Comment by misto** [comment]
Thank you very much for your help! The Component.js is just

```
import React from "react"
import { Trans } from "react-i18next"

export default function() {
  return (
    <div>
      <Trans i18nKey="key" />
    </div>
  )
}
```

Just to make sure, that should basically work out of the box, right? Or at least with the config I have. Since I don't use any private class elements I edited the code of `acorn-private-class-elements` to just skip whatever it wants to do and then I again end up with the `SyntaxError: Unexpected token (7:20)` from above. If I understand the 7:20 correctly, this points to the `=`. :confused:

**Comment by cheton** [comment]
I just added your code into the tests (under [test/fixtures](https://github.com/i18next/i18next-scanner/tree/master/test/fixtures)) but I didn't find any problems to your code.

Did you remove package-lock.json as well when removing node_modules for fresh install?

**Comment by misto** [comment]
That did it! :-) Thank you very much!

**Comment by kenzouno1** [comment]
same this issue. If i use parseFuncFromString and in jsx has delete will throw this error

**Comment by cutterbl** [comment]
@kenzouno1 I had the same issue. I completely removed my 'lock' file, deleted node-modules, reinstalled (including latest acorn as a dependency), and still got the errors. I finally got around it by adding a "resolutions" entry to my package.json, pointing to the internal acorn version.

```
"resolutions": {
    "i18next-scanner/**/acorn": "6.1.1"
  }
```
