### ISSUE TITLE
loadPath supports .js or .tsx

### ISSUE THREAD

**Issue by sibelius** [i18next/i18next-scanner#144]
my load path is a tsx typescript file

does this work with i18next-scanner?

**Comment by daliusd** [comment]
https://github.com/nucleartux/i18next-scanner-typescript

**Comment by daliusd** [comment]
As well look this discussion https://github.com/i18next/i18next-scanner/issues/88

**Comment by sibelius** [comment]
the problem is here https://github.com/i18next/i18next-scanner/blob/master/src/parser.js#L280

I think using json is a good approach for now

tks
