### ISSUE TITLE
Cannot parse dynamic imports

### ISSUE THREAD

**Issue by tquiroga** [i18next/i18next-scanner#147]
Is there a way to parse react components using `lazy()` or any other kind of dynamic imports?

To reproduce just try parsing a jsx file with a dynamic import such as:
```
import React, { lazy } from 'react'
const MyComponent = lazy(() =>
  import('components/MyComponent')
);
```

#### Version
- i18next: <i>1.0.0-beta34</i>
- i18next-scanner: <i>2.10.01</i>

**Comment by cheton** [comment]
Unlike babel or other transpilers, i18next-scanner parses component according to [your input files](https://github.com/i18next/i18next-scanner/blob/master/examples/i18next-scanner.config.js#L5-L11), not the import statements.

You can define your input files as listed in this example:
https://github.com/i18next/i18next-scanner/blob/master/examples/i18next-scanner.config.js

**Comment by tquiroga** [comment]
Thanks @cheton , I have tried using `input` to reject the files that are using dynamic components.
```
  input: [
    '!resources/client/AppRoot.js',
    '!resources/client/features/app/components/App/App.js',
    '!resources/client/features/onboarding/containers/OnboardingSetupContainer.js',
    'resources/client/**/*.{js,jsx}',
    // Use ! to filter out files or directories
    '!**/node_modules/**',
  ],
```
But I still get the same error:
```
i18next-scanner: Unable to parse Trans component from "/Users/rooser/WebApps/rooser/resources/client/AppRoot.js"
    TypeError: baseVisitor[type] is not a function
i18next-scanner: Unable to parse Trans component from "/Users/rooser/WebApps/rooser/resources/client/features/app/components/App/App.js"
    TypeError: baseVisitor[type] is not a function
i18next-scanner: Unable to parse Trans component from "/Users/rooser/WebApps/rooser/resources/client/features/onboarding/containers/OnboardingSetupContainer.js"
    TypeError: baseVisitor[type] is not a function```

Note these are the only 3 files I use dynamic import in.  Is there any way I can tweak the options `trans` to ignore files?

**Comment by jamesknelson** [comment]
As a temporary fix, you can add the following to your `i18next-scanner.config.js`:

```js
const { base } = require("acorn-walk");

Object.assign(base, {
  Import() {}
});
```

@cheton The issue seems to be that acorn currently fails when files include dynamic imports, i.e. `import()`. This is because they're still just a proposal. Given how common they are (e.g. they're supported by create-react-app), it might be worth adding an `Import() {}` line to `acorn-jsx-walk.js` just to fix this in the meantime.

**Comment by cheton** [comment]
Thanks @jamesknelson and @tquiroga 

Dynamic imports is now supported in [v2.10.2](https://github.com/i18next/i18next-scanner/releases/tag/v2.10.2)
