### ISSUE TITLE
Merge projects?

### ISSUE THREAD

**Issue by karellm** [i18next/i18next-scanner#19]
I'm the author of [i18next-parser](https://github.com/i18next/i18next-parser). When you created the project github auto subscribed me to the notifications and I thought that I'd say hi.

Do you want to collaborate rather than maintaining two similar projects?

**Comment by cheton** [comment]
Hi karellm,

I'm glad to hear that. The main reason I created the tool for our projects is that we need to support various kinds of i18n usage, not just the default `t()` function. For examples:

1. Using a keyless approach (a.k.a. hashed-key) like [i18next-text](https://github.com/cheton/i18next-text)
   ```js
   var i18n = require('i18next');
   i18n._ = require('i18next-text'); // extends i18next to provide a new _() method

    i18n.setLng('en');
    i18n.t('loading'); // will return "Loading..."
    i18n._('Loading...', {lng: 'de'}); // will return "Wird geladen..."
    i18n._('No longer to specify the key. Save your time and work more efficiently.');
  ```
  to locate missing translation:
  ```js
  var strNotTranslated = '<span class="highlight error">STRING_NOT_TRANSLATED</span>';
  i18n._('YouTube has more than one billion users each month.', {
    defaultValue: strNotTranslated
  });
  ```
  Also see https://github.com/cheton/i18next-text#translation-features

2. Custom i18n helper in Handlebars
  ```html
  {{i18n 'Basic Example'}}
  {{i18n '__first-name__ __last-name__' first-name=firstname last-name=lastname}}
  {{i18n 'English' defaultKey='locale:language.en-US'}}
  {{i18n defaultKey='loading'}}
  {{#i18n}}Some text{{/i18n}}
  {{#i18n this}}Description: {{description}}{{/i18n}}
  {{#i18n this last-name=lastname}}{{firstname}} __last-name__{{/i18n}}
  ```
  with the context:
  ```js
  var source = fs.readFileSync('./handlebars-helper-i18n.hbs'), 'utf-8');
  var template = handlebars.compile(source);
  var context = {
      'firstname':'Foo',
      'lastname':'Bar',
      'description': 'Foo Bar Test'
  };
  console.log(template(context));
  ```
  and it will output to the console like so:
  ```html
  Basic Example
  Foo Bar
  English
  Loading...
  Some text
  Description: Foo Bar Test
  Foo Bar
  ```


#####   A [demo](http://jsfiddle.net/cheton/fo8Lgact/) for above examples is available on jsFiddle.


I'm quite pleased to see if we can combine our results into one. Do you have any recommended way for the collaboration?

**Comment by karellm** [comment]
@cheton I don't currently use `i18next-parser` but it still gets a lot of downloads so I keep supporting it and can't discontinue it.

What I can offer is to open you the door to the `i18next-parser`. You could build the features you mentionned into the parser (I can grant you access to the repo). As to my personal contribution, I can offer to answer any question you would have about the existing codebase, discuss future implementations and review PRs. I won't be writing a lot of code for it though. 

Let me know if it is something you are interested in.

**Comment by cheton** [comment]
It sounds great, we can go this way. Just to let you know I'm busy preparing a speech for JSDC in Oct, so I will be able to start working around Nov.

**Comment by karellm** [comment]
Sounds good. I'm usually pretty reactive on github, just ping me when you are ready.
