### ISSUE TITLE
Getting full key path as the key in defaultValue callback

### ISSUE THREAD

**Issue by ekeuus** [i18next/i18next-scanner#196]
## 🐛 Bug Report

I want to add a "translation mode" language, where all original keys (user_page::form::label) should be used as the values of the nested json object keys ("user_page::form::label"). The separator that we are using is "::". For some reason tho, only the last "label" part is provided to the defaultValue callback, meaning it is not possible to get the full path line that.

Is there a way to do that or can I open up a PR to somehow implement it?

**Comment by ekeuus** [comment]
Just using "cimode" as the locale is good enough as it will expose the keys.

**Comment by nitaybz** [comment]
can you please provide an example config? I really want to show the string file path as the key of the json object

**Comment by ekeuus** [comment]
Set cimode as the locale instead of "en" and that should work :)

**Comment by nitaybz** [comment]
You mean as language? I don't see a way to set locale

**Comment by ekeuus** [comment]
I misunderstood. I didn't need the full key in the end for my use case. I could just resolve my problem with using cimode.

Not sure how you'd get access to the full key there 🤷
