### ISSUE TITLE
CI integration

### ISSUE THREAD

**Issue by ImADrafter** [i18next/i18next-scanner#197]
First of all, I would like to thank you the work, hours and effort being put in this library.

## 🚀 Feature Proposal

Expose certain keys in the for CI integration (jenkins, GH Actions).

## Motivation

In my team, we already have a Continuous Integration proccess. We would love if we can also, add a side process to check if any translation is missing, using i18next-scanner. Like checking in the hole loadPath, and search for the defaultValue, and if it finds any, exit the process.

## Example
```js
// i18next-scanner.config.js
module.exports = {
        defaultLng: 'en',
        defaultNs: 'resource',
        defaultValue: (lng, ns, key) =>  '__MISSING_TRANSLATION_',
        // ... rest of config
        throwOnMissingKey: true | false,
};
```

**Comment by markdon** [comment]
i18next-scanner doesn't appear to already have any features that are outside the process of static code analysis and translation file generation. Unless you wanted to throw in the middle of generating translation files, adding an option that runs a completely seperate process seems inappropriate. 

Searching for untranslated strings would be reasonably easy to do in a standalone node.js script. Import your config to get defaultValue, globby to find all your translation files, fs.readFile, JSON.parse, loop through all files and keys.

**Comment by ImADrafter** [comment]
Ok, thank you @markdon for your answer. I guess adding a separate process could be expensive, and maybe just a few users are interesting. Closing FTM, TY!
