### ISSUE TITLE
Extraction of translation values

### ISSUE THREAD

**Issue by arjyamishra** [i18next/i18next-scanner#20]
I am using this plug-in for the extraction of translation key and it's corresponding value from html files. After executing my gulp task, translation keys are extracted but with blank (" ") values. Am I missing any configuration??

Html text:
`<h2 data-i18n="home.DefaultKey">Some Text</h2>`

Gulp task:

```
var gulp = require('gulp');
var i18next = require('i18next-scanner');

gulp.task('i18nextScan', function () {
    return gulp.src('src/**/*.html')
        .pipe(i18next({
            // a list of supported languages
            lngs: ['en'],

            // the source path is relative to current working directory
            resGetPath: 'locale/__lng__/__ns__.json',

            // the destination path is relative to your `gulp.dest()` path
            resSetPath: '__lng__/__ns__.json'
        }))
        .pipe(gulp.dest('locale'));
});
```

Output generated:
path: locale/en/translation.json

```
{
    "home": {
        "DefaultKey": ""
      }
}
```

**Comment by cheton** [comment]
In current version, `i18next-scanner` has limited support for extracting default values that specified with the `data-i18n` attribute. As you might already know, the default value can not only be inner html/text, but also in the form of multiple html attributes. For example:
```html
<div data-i18n="[title]t.title" title="defaultTitle"></div>
<input data-i18n="[placeholder]t.placeholder;[value]t.value"
    placeholder="defaultPlaceholder"
    value="defaultValue">
<h2 data-i18n="home.DefaultKey">Some Text</h2>
```

To extract all default values with above example, it requires a HTML parser to parse other attributes as well as the `data-i18n` attribute. It might take me some time to do this.

**Comment by joharzmn** [comment]
Anyone know how to get default values from innerHtml ?
