### ISSUE TITLE
Scanner throwing SyntaxError when using the new double question mark(??) operator

### ISSUE THREAD

**Issue by Aghamyr** [i18next/i18next-scanner#202]
## 🐛 Bug Report

When using the new ES2020 double question mark operator, scanner throw a syntaxError

## To Reproduce

Just add this operator in any file scanned for translation

```js
let test = selectMonth.year ?? 0;


i18next-scanner: Unable to parse Trans component:
SyntaxError: Unexpected token (122:34)
```
line 122 being the line of the ?? operator in this example
It says unbable to parse Trans component but the Trans component in the file is not the issue, if I remove the operator it doesn't throw anymore
## Expected behavior

The scan should finish normally

## Your Environment

- *runtime version*: node v14, express, gulp
- *i18next version*: 19.4.5
- *i18next-scanner version*: latest
- *os*: Windows
- *any other relevant information*

**Comment by cheton** [comment]
Nullist coalescing operator (??) is now supported in [i18next-scanner@3.0.0](https://github.com/i18next/i18next-scanner/releases/tag/v3.0.0).

**Comment by pkhodaveissi** [comment]
I have the same issue with:
Javascript Null Propagation Operator, (var1?.var2)
