### ISSUE TITLE
Option to cull unused translations

### ISSUE THREAD

**Issue by hbnrmx** [i18next/i18next-scanner#207]
## 🚀 Feature Proposal

A boolean option to cull translations that aren't used in the source code.

## Motivation

We have a large number of existing translations and our new application only needs to use a subset of them.
It would be great to be able to analyze which keys are in use and discard the rest.

## Example

User can specify whether he would like to keep the unused translations in the output file.

**Comment by markdon** [comment]
Is [`removeUnusedKeys`](https://github.com/i18next/i18next-scanner#removeunusedkeys) what you're looking for?

**Comment by hbnrmx** [comment]
I'm baffled how I managed to miss that. Thank you very much!
