### ISSUE TITLE
Add support to disable the keyseparator

### ISSUE THREAD

**Issue by Xevi** [i18next/i18next-scanner#21]
From `i18next` documentation you can setup the library to support a key as a value fallback, in that case the documentation allows you to define the keyseparator option to false as follows:

http://i18next.com/translate/keyBasedFallback/

**Comment by cheton** [comment]
I will add this feature in next release.

**Comment by Xevi** [comment]
Thanks for the answer I already fixed it and opened a PR. 

I hope the code is not too bad :) let me know if you prefer I open the PR using a specific release branch as a target branch.

Cheers.

**Comment by cheton** [comment]
In addition to `keyseparator`, I will add the check for `nsseparator` as well.

**Comment by cheton** [comment]
Published in [v0.6.0](https://github.com/i18next/i18next-scanner/releases/tag/v0.6.0)
