### ISSUE TITLE
json format v4

### ISSUE THREAD

**Issue by sm2017** [i18next/i18next-scanner#224]
## To Reproduce

```js
i18next.t("car", { count: 1 });
```
I have "en-US", "fa-IR" locales the scanner produce

```
i18next-scanner: Added a new translation key { "car": "car" } to "src/locales/en-US/translation.json"
i18next-scanner: Added a new translation key { "car_plural": "car" } to "src/locales/en-US/translation.json"
i18next-scanner: Added a new translation key { "car_0": "car" } to "src/locales/fa-IR/translation.json"
```

`car_0` is json format v3

**Comment by Elindorath** [comment]
If you can migrate to the other extractor [i18next-parser](https://github.com/i18next/i18next-parser), it supports JSON format v4.
There is [an ongoing discussion](https://github.com/i18next/i18next-scanner/issues/216) about merging those two tools
