### ISSUE TITLE
`key_one` and `key_other` instead of `key` and `key_plural`

### ISSUE THREAD

**Issue by strarsis** [i18next/i18next-scanner#228]
## 🐛 Bug Report
`i18next-scanner` currently generates plural keys with key and `_plural` postfix:
````
  "countLabel": "{{count}} item",
  "countLabel_plural": "{{count}} items"
````

However, it doesn't work with current `i18next`/`react-i18next`, the current [`i18next` documentation lists plural keys with `_one` and `_other` postfixes](https://www.i18next.com/translation-function/plurals#singular-plural), and it worked after manually changing the generated keys to use this schema instead:
````
  "countLabel_one": "{{count}} item",
  "countLabel_other": "{{count}} items"
````

## To Reproduce
- Add a plural `i18next` key: `t('countLabel', { count: 100 })` to the project code.
- Run the configured `i18next-scanner` on that project.
- Inspect the generated keys, note that the `key`/`key_plural` scheme is used.
Also `i18next`/`react-i18next` is unable to use the keys.
````
  "countLabel": "{{count}} item",
  "countLabel_plural": "{{count}} items"
````

## Expected behavior
Plural keys are generated in a schema that works with current `i18next`/`react-i18next`.
````
  "countLabel_one": "{{count}} item",
  "countLabel_other": "{{count}} items"
````

## Your Environment

- *runtime version*: `v16.14.2`
- *i18next version*: `3.1.0`
- *os*: Linux (Ubuntu LTS on WSL 2 on Windows 10)

**Comment by speto** [comment]
@strarsis 
There is hardcoded `compatibilityJSON: 'v3',` in [i18next-scanner parser.js:22](https://github.com/i18next/i18next-scanner/blob/master/src/parser.js#L22) which uses numerical suffixes (`_0`,`_1`,`_2`,...) instead of alpha form (`_one`, `_few`, `_others`,...)

You could continue using i18next-scanner and set v3 in options of your project `i18next.init()` accordingly to fix incompatibility of keys:
```
i18next.init({
  ...,
  compatibilityJSON: 'v3',
});
```
or switch to [i18next-parser](https://github.com/i18next/i18next-parser) which supports v4 format as you want

**Comment by basslagter** [comment]
I am stumbling into this issue as well. As I want to go along with the new v4 format this `compatibilityJSON` is not really an option. I gave i18next-parser a try and it seem to work well but it lacks support for `returnObject` in the options which is a no-go for me also. 

I am wondering why this cannot be fixed? Is this package no longer maintained (and is i18next-parser)?

**Comment by basslagter** [comment]
@speto is this project still alive?

**Comment by Maxou44** [comment]
Any plan to support JSON v4 ?

**Comment by strarsis** [comment]
+1! Re-encountered this issue today, with using the i18next v4 JSON format.
