### ISSUE TITLE
Trans component can't be parsed if boolean props exist.

### ISSUE THREAD

**Issue by geewoo94** [i18next/i18next-scanner#240]
## 🐛 Bug Report

Trans component can't be parsed if boolean props exist.

## To Reproduce
```js
// This is not parsed
<Trans
  i18nKey="some key"
  shouldUnescape
/>

// This way is ok
<Trans
  i18nKey="some key"
  shouldUnescape={true}
/>
```

## Expected behavior

Should be parsed correctly.

## Your Environment

- *runtime version*: node v16.16.0
- *i18next version*: "^21.6.11"
- *i18next-scanner version*: "^4.1.0"
- *os*: Mac

**Comment by cheton** [comment]
Fixed in 4.1.1
