### ISSUE TITLE
glob-parent before 5.1.2 vulnerable to Regular Expression Denial of Service in enclosure regex

### ISSUE THREAD

**Issue by adamkui** [i18next/i18next-scanner#247]
## 🐛 Bug Report

The following dependency path is having a high level vulnerability, that was already fixed in glob-parent package. This needs to be fixed by upgrading the package versions.
i18next-scanner > vinyl-fs > glob-stream > glob-parent 

## To Reproduce

1.) Install i18next-scanner at latest version. 
2.) Run npm audit / yarn audit.
3. See vulnerability in report.

## Expected behavior

The vulnerability should be removed by having newer versions of the listed packages.

## Your Environment

- *runtime version*: Node.js v16.17.0
- *i18next version*: 4.2.0
- *os*: Mac

**Comment by cheton** [comment]
Fixed in d54293b5d008cd2164d6f961a6a16280db6cfad2
