### ISSUE TITLE
Error when comparing file extensions in transform function

### ISSUE THREAD

**Issue by ErikGronlund** [i18next/i18next-scanner#25]
Hi,

I think there is an error in the transform function when comparing file extensions with extentions from options. extname should be compared against options.attr.extensions and options.func.extensions instead of options.attr.list and options.func.list.

        if (_lodash2.default.isObject(options.attr) && _lodash2.default.includes(options.attr.list, extname)) {
            // Parse attribute (e.g. data-i18n="key")
            parser.parseAttrFromString(content);
        }

        if (_lodash2.default.isObject(options.func) && _lodash2.default.includes(options.func.list, extname)) {
            // Parse translation function (e.g. i18next.t('key'))
            parser.parseFuncFromString(content);
        }

should probably be

        if (_lodash2.default.isObject(options.attr) && _lodash2.default.includes(options.attr.extensions, extname)) {
            // Parse attribute (e.g. data-i18n="key")
            parser.parseAttrFromString(content);
        }

        if (_lodash2.default.isObject(options.func) && _lodash2.default.includes(options.func.extensions, extname)) {
            // Parse translation function (e.g. i18next.t('key'))
            parser.parseFuncFromString(content);
        }

**Comment by cheton** [comment]
Ooops...My bad!
Thank you for telling me this. I will fix it soon. 

Source code:
https://github.com/i18next/i18next-scanner/blob/master/src/index.js#L14
https://github.com/i18next/i18next-scanner/blob/master/src/index.js#L19

**Comment by cheton** [comment]
Fixed in [v1.0.2](https://github.com/i18next/i18next-scanner/releases/tag/v1.0.2)

**Comment by ErikGronlund** [comment]
Thanks!
