### ISSUE TITLE
Disabiling nsSeparator breaks the defaultValue fallback

### ISSUE THREAD

**Issue by difelice** [i18next/i18next-scanner#27]
When _nsSeparator_ is `false`, translation will not fallback to _defaultValue_:

https://github.com/i18next/i18next-scanner/blob/master/src/parser.js#L367

If key is missing the _defaultValue_ should take place even without _nsSeparator_.

Thanks.

**Comment by cheton** [comment]
Thanks for reporting this issue.

How about changing the line [#L368](https://github.com/i18next/i18next-scanner/blob/master/src/parser.js#L368) to this:
```js
res[elem] = _.isUndefined(defaultValue) ? elem : defaultValue;
```

**Comment by cheton** [comment]
Just for confirmation - what you mentioned above should be related to `keySeparator`, not `nsSeparator`?

**Comment by difelice** [comment]
Yes, that line doesn't seem to be the issue, but yes having `nsSeparator: false` ignores the _defaultValue_, any other setting works fine.

**Comment by cheton** [comment]
Here is current expected result by setting both `nsSeparator` and `keySeparator` to <i>false</i>. It will use the key as its value for missing keys:
https://github.com/i18next/i18next-scanner/blob/master/test/index.js#L52

```js
{
    "Loading...": "Loading...",
    "This value does not exist.": "This value does not exist.",
    "YouTube has more than __count__ billion users.": "YouTube has more than __count__ billion users."
}
```

From your expectation, I can change this to use the <i>defaultValue</i> option if it's provided. For example:
```js
{ // options
    defaultValue: '__NOT_TRANSLATED__',
    nsSeparator: false,
    keySeparator: false
}
```

and generate the output:
```js
{
    "Loading...": "__NOT_TRANSLATED__",
    "This value does not exist.": "__NOT_TRANSLATED__",
    "YouTube has more than __count__ billion users.": "__NOT_TRANSLATED__"
}
```

Please correct me if i have any misunderstanding above.

**Comment by difelice** [comment]
Yes , that's exactly right. If key is missing, defaultValue should be user not if _nsSeparatod_ and/or _keySeparator_ are `false`.

**Comment by cheton** [comment]
Good. I'd like to make two types of the `defaultValue` option - string or function

* If <i>defaultValue</i> option is a type of string, it will be used for all missing keys.
* If <i>defaultValue</i> option is a type of function, you can customize the return value depending on different scenarios (e.g. return original key for <b>en</b> language, and return defaultValue for other languages).

**Comment by cheton** [comment]
https://github.com/i18next/i18next-scanner/releases/tag/v1.1.0

Fixes issue <b>#27 - Disabiling nsSeparator breaks the defaultValue fallback</b>

Now the <i>defaultValue</i> option can either be a string or a function. For example:

* Provides the default value with a string
```js
{
    defaultValue: '__NOT_TRANSLATED__'
}
```

* Provides the default value as a callback function
```js
{
    // @param {string} lng The language currently used.
    // @param {ns} ns The namespace currently used.
    // @param {key} key The translation key.
    // @return {string} Returns a default value for the translation key.
    defaultValue: function(lng, ns, key) {
        if (lng === 'en') {
            // Return key as the default value for English language
            return key;
        }
        // Return the string '__NOT_TRANSLATED__' for other languages
        return '__NOT_TRANSLATED__';
    }
}
```

**Comment by cheton** [comment]
Please have a check with v1.1.0, and let me know if you have any problems. Thanks.

**Comment by difelice** [comment]
The _defaultValue_ as function is perfect for **base language** build. Thank you!

**Comment by difelice** [comment]
Sorry I forgot to close it. I confirm it's working. Thank you so much!

**Comment by cheton** [comment]
It's okay! Just let me know if you have any problems. Thanks.
