### ISSUE TITLE
Singular and Plural

### ISSUE THREAD

**Issue by difelice** [i18next/i18next-scanner#28]
Is there a workaround to support Plurals?: http://i18next.com/translate/pluralSimple/

**Comment by cheton** [comment]
Hmmm! I used to manage plural keys manually within resource files since it's not an easy thing using regular expressions to determine plural keys from JS code. Have you encountered any problems on that?

**Comment by difelice** [comment]
I'm trying to add it as a feature: https://github.com/i18next/i18next-scanner/compare/master...difelice:add-plural-support

I might need some help ;-)

**Comment by cheton** [comment]
It looks cool! I will help review the code by tomorrow.

**Comment by difelice** [comment]
Thank you!

**Comment by cheton** [comment]
I found something changed in your regular expression, the `\'(?:[^\'\\\\]|\\\\.)*\'` was replaced by `\'(?:[^\'\\\\]|\\.)*\'`, this will not work for a quote character (`'` or `"`) within a quoted string. For example: 

```js
var value = i18n.t('It\'s good!');
```

You can see the difference between them:
```js
var code = 'var value = i18n.t(\'It\\\'s good!\')';

var re1 = '\'(?:[^\'\\\\]|\\.)*\''
code.match(new RegExp(re1));
// → ["'s good!'"]

var re2 = '\'(?:[^\'\\\\]|\\\\.)*\''
code.match(new RegExp(re2));
// → ["'It\'s good!'"]
```

**Comment by cheton** [comment]
References:
Extracting the JSON string from given text 
http://stackoverflow.com/questions/21994677/find-json-strings-in-a-string

**Comment by cheton** [comment]
Actually I had some codes like this, so a regular expression may not work properly.
```js
i18n.t('The group "{{group}}" contains more than {{count} customers.', {
    group: (function(id) {
        // processing...
        return 'xxxxx'; 
    })(groupId),
    count: 2
});
```

I have an idea of using the [matchRecursive](http://blog.stevenlevithan.com/archives/javascript-match-nested) function to match the code within braces `{...}`, then pass the enclosed string `({...})` to the [Esprima](http://esprima.org/demo/parse.html) parser. Therefore, I can get the expected result by querying key name equals to `count` from the properties array:
```
var esprima = require('esprima');
var code = '({
    group: (function(id) {
        // processing...
        return 'xxxxx'; 
    })(groupId),
    count: 2
})';

var r = esprima.parse(code);

r.body[0].expression.properties.forEach(function(prop) {
    if (prop.name === 'count') { // matched }
});
```

The object returned by above `esprima.parse`:
```
{
    "type": "Program",
    "body": [
        {
            "type": "ExpressionStatement",
            "expression": {
                "type": "ObjectExpression",
                "properties": [
                    {
                        "type": "Property",
                        "key": {
                            "type": "Identifier",
                            "name": "group"
                        },
                        "computed": false,
                        "value": {
                            "type": "CallExpression",
                            "callee": {
                                "type": "FunctionExpression",
                                "id": null,
                                "params": [
                                    {
                                        "type": "Identifier",
                                        "name": "id"
                                    }
                                ],
                                "defaults": [],
                                "body": {
                                    "type": "BlockStatement",
                                    "body": [
                                        {
                                            "type": "ReturnStatement",
                                            "argument": {
                                                "type": "Literal",
                                                "value": "xxxxx",
                                                "raw": "'xxxxx'"
                                            }
                                        }
                                    ]
                                },
                                "generator": false,
                                "expression": false
                            },
                            "arguments": [
                                {
                                    "type": "Identifier",
                                    "name": "groupId"
                                }
                            ]
                        },
                        "kind": "init",
                        "method": false,
                        "shorthand": false
                    },
                    {
                        "type": "Property",
                        "key": {
                            "type": "Identifier",
                            "name": "count"
                        },
                        "computed": false,
                        "value": {
                            "type": "Literal",
                            "value": 2,
                            "raw": "2"
                        },
                        "kind": "init",
                        "method": false,
                        "shorthand": false
                    }
                ]
            }
        }
    ],
    "sourceType": "script"
}
```

**Comment by cheton** [comment]
Hi @difelice,

Just had a question about this diff:
https://github.com/i18next/i18next-scanner/compare/master...difelice:add-plural-support#diff-6947033678b93d106e25614dd972e66fR389

```js
+ // Remove plural suffix from translation
+ res[elem] = res[elem].replace(new RegExp(options.pluralSeparator + 'plural$'), '');
```

May I know the purpose of removing plural suffix from translation while adding a new entry?

**Comment by difelice** [comment]
Yes, I like the Esprima solution, you're right about the RegExp, it won't cover most scenarios. 

About the suffix, I'm adding a virtual key with the plural suffix and this is not part of the original text:

Parser now creates two keys and base language translation:
```
"You have {{count}} messages": "You have {{count}} messages",
"You have {{count}} messages_plural": "You have {{count}} messages_plural"
```

Removing the suffix leaves the base language un touched: 
```
"You have {{count}} messages": "You have {{count}} messages",
"You have {{count}} messages_plural": "You have {{count}} messages"
```

Thanks!

**Comment by cheton** [comment]
Thanks for reminding me. I just come up with an idea that can also leave the translation untouched. This will use previous value as the <i>defaultValue</i>, so we don't need to remove it afterwards:
```js
this.set(key + this.options.pluralSeparator + 'plural', this.get(key));
```

You can check out the modifications in dev branch:
https://github.com/i18next/i18next-scanner/blob/dev/src/parser.js#L172

**Comment by cheton** [comment]
Whoops! Just found a bug with above code, it will not work with the [defaultValue](https://github.com/i18next/i18next-scanner#defaultvalue) option. 😿 

I may use another way like below to provide more flexibility, since many other languages may not have or may have more than two [plural forms](http://i18next.com/translate/pluralMulti/) representation:
```js
this.set(key, null, { resolvePlural: true });

```

**Comment by cheton** [comment]
This issue has been fixed in the dev branch, I will do more tests with my projects by tomorrow. If no issues are found, I will merge it to the master branch and publish a v1.2.0 release.

**Comment by cheton** [comment]
Both Plural and Context syntax are now supported since [v1.2.0](https://github.com/i18next/i18next-scanner/releases/tag/v1.2.0).

**Comment by difelice** [comment]
That's great news!! Thank you!
