### ISSUE TITLE
Consider parsing `ns` from function call

### ISSUE THREAD

**Issue by p-j** [i18next/i18next-scanner#36]
First, thanks for the package, its already helping us manage projects with i18next translations.

In the spirit of making translation easier on our international team and more manageable for us, I was woundering if you would consider parsing the namespace if provided?

[I saw reading the source](https://github.com/i18next/i18next-scanner/blob/master/src/parser.js#L269) that you parse `defaultValue` `context` and `count` from a hypothetical `option` object that would be provided to a `i18next.t()` call, is there a reason I am missing (apart from not needing the feature so far) not to parse the namespace the same way ?

For instance : 
```js
i18next.t('This is a test string', { ns: 'notYourDefaultNS' })
```

Would result in the `'This is a test string'` key to be added to the `notYourDefaultNS` namespace instead of the default one like now.

**Comment by cheton** [comment]
That's indeed a missing part in the i18next-scanner. Thanks for your PR, it looks good to me. I will make a new update and publish to NPM by tomorrow.

**Comment by p-j** [comment]
:+1:

**Comment by cheton** [comment]
v1.5.0 has been published to NPM. Thank you for the improvement.
