### ISSUE TITLE
Multiple keys created when context used

### ISSUE THREAD

**Issue by othrayte** [i18next/i18next-scanner#38]
#### Version
- i18next: <i>3.5.2</i>, also occurs with <i>7.1.1</i>
- i18next-scanner: <i>1.5.1</i>

#### Configuration
```js
{ // i18next-scanner options
	func: {
		list: ["t"],
	},
	keySeparator: false,
	nsSeparator: false,
}
```

This occurs with the items from the unit test "Context".

If extracting just:
```i18next.t('friend', {context: 'male'});```

The resulting translations get extracted:

```js
        en: {
            translation: {
                "friend": "",
                "friend_male": "",
            }
        }
```

I'm unable to run the unit tests in this repo but it appears that this isn't seen because the test extracts the translations that use and don't use the context together and the issue is hidden.

**Comment by jamuhl** [comment]
i think the result is correct key `friend` acts as a fallback if you provide a context that is not existing in translations. see: http://i18next.com/translate/context/

**Comment by cheton** [comment]
@othrayte 

A fallback is needed if a context does not exist in other places. If you really don't need the fallback, I can add a boolean option like `contextFallback` or something else that can be used to enable or disable adding fallback key when a context found.

**Comment by jamuhl** [comment]
if no fallback needed one could define a normal keys instead of using context i think, like `i18next.t('friend.male');` but not the boss here ;)

**Comment by othrayte** [comment]
Hmm, I suppose this is a difference in the way I'm using the keys as I'm using the [Key Based Fallback](http://i18next.com/translate/keyBasedFallback/) support and then to give more context to the translators I'm specifying a context, and thus don't want the key without the context aswell. In this case I'm not able to provided the extra context in the translation key as it is the fallback/default translation.

For my case an option to exclude the fallback would be much appreciated.

The actual reason that I created this test case was I was working with pluralisation. In this case I pass the results of i18next-scanner to i18next-conv to create .po files. This tool doesn't recognise the need for pluralisation if the key is present by itself as well as with a context and also with both the context and the pluralisation.

E.g.
If extracting just:
i18next.t('ambiguous text', {context: 'clarifying context', count: 5});

```js
en: {
    translation: {
        "ambiguous text": "",
        "ambiguous text_clarifying context": "",
        "ambiguous text_clarifying context_plural": "",
    }
}
```

I think the conversion tool expects the fallback to also have a pluralisation, which I think is sensible. See https://github.com/i18next/i18next-gettext-converter/blob/c8f5f99cc906bd77a2bc32d950d422c7cb7581da/test/_testfiles/en/translation.utf8_msgid.json.

So maybe the real issue is the lack of a pluralisation of the fallback key without the context.
E.g.
```js
en: {
    translation: {
        "ambiguous text": ""
        "ambiguous text_plural": "", // <-- missing
        "ambiguous text_clarifying context": "",
        "ambiguous text_clarifying context_plural": "",
    }
}
```

**Comment by cheton** [comment]
You can check out new options in the [1.7.0 release](https://github.com/i18next/i18next-scanner/releases/tag/v1.7.0). 

#### context

Type: `Boolean` Default: `true`

Whether to add context form key.

#### contextFallback

Type: `Boolean` Default: `true`

Whether to add a fallback key as well as the context form key.

#### contextSeparator

Type: `String` Default: `'_'`

The character to split context from key.

#### plural

Type: `Boolean` Default: `true`

Whether to add plural form key.

#### pluralFallback

Type: `Boolean` Default: `true`

Whether to add a fallback key as well as the plural form key.

#### pluralSeparator

Type: `String` Default: `'_'`

The character to split plural from key.
