### ISSUE TITLE
How can we just modify a existing file ?

### ISSUE THREAD

**Issue by workzer** [i18next/i18next-scanner#40]
Hi,
I actually use i18next-scanner with vinyl-fs as many exemple, my problem is, when i parse my main file, it overwrite with new informations (json) so I lost with that all my values.

Do you have any solution to just modify property if the file already exist ?

Cordially.

**Comment by cheton** [comment]
I don't quite understand your question. Only files specified with `lngs` and `ns` will be overwritten:
```js
{
    lngs: ['en'],
    ns: ['translation']
}
```
Could you provide a practical example for what values will lost after running i18next-scanner? Thank you.

**Comment by workzer** [comment]
I'm sorry, my explanation was so bad.

So let say that I have a main file __index.html__ which have some i18next function and attribute.

I use the code like that to create all my *.json files:
```javascript
vfs.src([__dirname + '/../app/index.html'])
.pipe(scanner({
  lngs: ['en', 'fr'],
  sort: true,
  attr: {
    list: ['data-i18n'],
    extensions: ['.html', '.htm']
  },
  func: {
      list: ['i18next.t', 'i18n.t'],
      extensions: ['.js', '.jsx', '.html', '.htm']
  },
  resource: {
      loadPath: 'i18n/{{lng}}.json',
      savePath: 'i18n/{{lng}}.json',
  }
}))
.pipe(vfs.dest(__dirname + '/../app/'));
```

So I have my folder i18n which contain my file en.json and fr.json, for this part everything is fine.

My problem is, If I actualize my __index.html__ and that I execute the code above, the result is that it overwrite my en.json and fr.json with a new json so It doesn't care about the data inside my actual [en, fr] file to just actualise those.

My question is, do you have any solutions to actualize data, not only overwrite them ?

**Comment by cheton** [comment]
First, you can try to turn on the [debug](https://github.com/i18next/i18next-scanner#debug) mode to get more verbose output.

According to your configuration file, your resource files were stored to "app/i18n/{{lng}}.json", but i18next-scanner resolved resources files from current working directory (i.e. "i18n/{{lng}}.json"). 
Then you will see the following output when turning on the debug mode:
```
Unable to load "i18n/en.json"
Unable to load "i18n/fr.json"
```

You can try using absolute paths to specify resource files. This configuration should resolve your issue:
```js
const vfs = require('vinyl-fs');
const scanner = require('i18next-scanner');
const path = require('path');

vfs.src([__dirname + '/../app/index.html'])
.pipe(scanner({
  debug: true,
  lngs: ['en', 'fr'],
  sort: true,
  attr: {
    list: ['data-i18n'],
    extensions: ['.html', '.htm']
  },
  func: {
      list: ['i18next.t', 'i18n.t'],
      extensions: ['.js', '.jsx', '.html', '.htm']
  },
  resource: {
      loadPath: path.join(__dirname, '../app/i18n/{{lng}}.json'),
      savePath: path.join(__dirname, '../app/i18n/{{lng}}.json')
  }
}))
.pipe(vfs.dest(__dirname + '/../app/'));
```

**Comment by workzer** [comment]
Hi, thank for your answer, my problem is not to use this code, the code that I put in my last message work perfectly.

Let imagine a scenario:

I put the code above  on a simple parser.js
I execute this file with node, then I can see my new folder __i18n__ with inside __en.json__ and __fr.json__, inside those files, I have all the property for use i18next, so perfect !

Now I change or add something in my index.html and I want translate this new thing so I execute again my file __parser.js__, my problem is now, this code analyse my file html and extract all keys (using by t() and data-i18n) then overwrite my first en.json and fr.json with the news json which contain all property this time but with that, I lost all my value so all my translation.

I don't know if you made something for this case or I have to make my own code to read all my files inside my folder __i18n__ and if some property are different, change the json.

**Comment by cheton** [comment]
On initialization, the parser will read your existing resource files and load them into resStore:
```js
try {
    const stat = fs.statSync(resPath);

    if (stat.isFile()) {
        this.resStore[lng][ns] = JSON.parse(fs.readFileSync(resPath, 'utf-8'));
    }
} catch (err) {
    this.debuglog('Unable to load ' + JSON.stringify(resPath));
}
```

For your case, assume that your current working directory is `src/gulp`, the formatted resPath will be `src/gulp/i18n/{{lng}}.json`, not the one like `src/app/i18n/{{lng}}.json`. You will see the `"Unable to load ..."` message when turning on the debug mode.

Since original resource files are failed to load, it will always generate new ones and overwrite your existing resource files after calling `vfs.dest(__dirname + '/../app/')` to flush stream.

To resolve this issue, you need to specify a correct resource path (either relative or absolute is fine) for initial loading, like so:
```js
resource: {
  loadPath: path.join(__dirname, '../app/i18n/{{lng}}.json'),
  savePath: path.join(__dirname, '../app/i18n/{{lng}}.json')
}
```

**Comment by jamuhl** [comment]
@workzer not sure but at some point (depending on your projects size and localization goal) you might need some translation management software. For that case we of i18next created http://locize.com - continuous localization is in the heart of it. New keys can be added by just enabling the saveMissing feature of i18next.

@cheton how is your code structured? would it be hard to extend that to have load/save using rest calls? If not we might do a PR to enable loading and saving directly from/to locize? (Thinking of it like the backend plugin in i18next?!?)

**Comment by workzer** [comment]
Thank you for everything @cheton , it's fine now.
Thank you also for your message @jamuhl but actually I want something totally free for this project, it's open source and I'll probably never make one penny with.
