### ISSUE TITLE
Broken npm install

### ISSUE THREAD

**Issue by NSLS** [i18next/i18next-scanner#43]
Hi. Yesterday I have faced an issue when trying to make `npm install` on a project, which has i18next-scanner. 

npm debug logs didn't give me much information, but by removing all the dependencies from my project and then trying to install each individually I have narrowed the problem to be with this particular library.

The error I'm facing looks like this:
![image](https://user-images.githubusercontent.com/8458382/28922332-5d25a3ac-7862-11e7-960d-5c776e6fcfac.png)

This might be a problem with one of the dependencies of this project or even with a dependency of their dependencies, however, all other libraries install without any error.

**Comment by cheton** [comment]
Please install i18next-scanner@2 and let me know if you still encountered this issue.
