### ISSUE TITLE
Expand README.md with how to merge translations

### ISSUE THREAD

**Issue by slaweet** [i18next/i18next-scanner#46]
Your README.md states
> Scan your code, extract translation keys/values, and merge them into i18n resource files.

But I couldn't find an example of how the "merge" part is done. How can I merge the extracted keys/values with existing translations?

I would expect it to be part of the [standard-api](https://github.com/i18next/i18next-scanner#standard-api) section

**Comment by cheton** [comment]
You can see the `loadPath` option at https://github.com/i18next/i18next-scanner#resource
It specifies the resource file path where you want to load existing translations.

**Gulpfile example**
```js
const gulp = require('gulp');
const sort = require('gulp-sort');
const scanner = require('i18next-scanner');

gulp.task('i18next', function() {
    return gulp.src(['src/**/*.{js,html}'])
        .pipe(sort()) // Sort files in stream by path
        .pipe(scanner({
            lngs: ['en', 'de'], // supported languages
            resource: {
                // the source path is relative to current working directory
                loadPath: 'assets/i18n/{{lng}}/{{ns}}.json',
                
                // the destination path is relative to your `gulp.dest()` path
                savePath: 'i18n/{{lng}}/{{ns}}.json'
            }
        }))
        .pipe(gulp.dest('assets'));
});
```

**Comment by cheton** [comment]
A real world example: https://github.com/cncjs/cncjs/blob/master/gulp/tasks/i18next.js

**Comment by LekovicMilos** [comment]
Can you update this link: https://github.com/cncjs/cncjs/blob/master/gulp/tasks/i18next.js ?

**Comment by cheton** [comment]
It's now a config file instead of a runnable script: https://github.com/cncjs/cncjs/blob/master/i18next-scanner.webconfig.js
