### ISSUE TITLE
Sorting of the keys when multiple levels are used

### ISSUE THREAD

**Issue by bubenkoff** [i18next/i18next-scanner#49]
#### Version
- i18next: <i>8.4.3</i>
- i18next-scanner: <i>2.0.1</i>

#### Configuration
```js
{ // i18next-scanner options
sort: true
}
```
When using multiple levels of the message id like: some.other.key sorting of the output json doesn't seem to work and outputs random order

**Comment by cheton** [comment]
Fixed in v2.0.2. Please let me know if it works for you.

**Comment by bubenkoff** [comment]
@cheton that was fast!
thanks a lot for taking care!
works like a charm!
