### ISSUE TITLE
Link element broken in Trans processing

### ISSUE THREAD

**Issue by wichert** [i18next/i18next-scanner#51]
Our use of parse5 to parse Trans element results in some interesting behaviour: parse5 enforces HTML rules, which can lead to unexpected results. See inikulin/parse5#219 for details.

The net result is that this input:

```html
 <Trans i18nKey="custom.label">
  I agree with the <Link to="/terms-and-conditions">terms</Link>.
</Trans>
```

becomes `I agree to the <1></1>terms.` – definitely not the desired result.

@cheton I'll try to deal with this one - I will need a fix in the next few days anyway.

**Comment by cheton** [comment]
Added in 2.0.3
