### ISSUE TITLE
cli output path insists on i18n directory

### ISSUE THREAD

**Issue by wichert** [i18next/i18next-scanner#54]
I'm playing with the new CLI. It seems to work well, except for one thing: it always creates an `i18n` directory, even if you specify `--output`. For example when I run this command:

```shell
yarn run i18next-scanner \
    --config config/i18next-scanner.js \
    --output public/locales \
    'src/**/*.{js,jsx}'
```

I want the output to be stored in `public/locales`. Instead the output is stored in `public/locales/i18n`.

**Comment by wichert** [comment]
This was my error - I missed the fact that you need to have an extra `options` key in the configuration file :(

**Comment by cheton** [comment]
I've been struggled whether to have an extra `options`, because I have to think of custom transform and custom flush functions, and I finally added the `options` key that is mainly for considering the future extensibility.

**i18next-config.js**
```js
{
    options: { },
    transform: function(file, enc, done) { },
    flush: function(done) { }
}
```

**Comment by wichert** [comment]
The config file structure is perfectly reasonable. I just missed the extra option key when I copied the config from my own cli script into the config file, something that people new to i18next-scanner probably won't do.

**Comment by cheton** [comment]
To display a warning message might help when the i18next-config.js file is misconfigured.
