### ISSUE TITLE
Backticks in functions are not handled correctly

### ISSUE THREAD

**Issue by wichert** [i18next/i18next-scanner#62]
With current git master the following two lines of code produce some very weird results:

```
i18next.t(`errors.${e.errors[key].result}`)
i18next.t(`errors.${defaultError}`)
```

The result looks like this:

```
     {                                                                  
       "en": {                                                          
         "translation": {                                               
           "errors": {                                                  
             "${defaultError}": "",                                     
             "${e": {                                                   
               "errors[key]": {                                         
                 "result}": ""                                          
               }                                                        
             }                                                          
           },                                                           
         }                                                              
       }                                                                
```

There is a workaround: either write the code to not use backticks like so:

```
i18next.t('errors.' + e.errors[key].result)
i18next.t('errors.' + defaultError)
```

or use a temporary variable and pass that to i18next.t.

**Comment by cheton** [comment]
Will it be helpful to ignore the key when an expression (i.e. `${expression}`) is detected within the backticks?

**Comment by wichert** [comment]
Yes, certainly. You could even do something a bit more drastic and ignore the key if backticks are used, since they should only be used for expressions anyway (and eslint will complain if you use them needlessly).

**Comment by jamesjryan** [comment]
+1 for this issue, experienced the same thing. Don't have time to check, but I believe even old fashioned string concatenation didn't work either - it was treating it literally.

**Comment by cheton** [comment]
Fixed in i18next-scanner@2.2.1

```js
// Ignore key with embedded expressions in string literals
if (firstChar === '`' && key.match(/\${.*?}/)) {
    continue;
}
```

**Comment by wichert** [comment]
Thanks!

**Comment by jamesjryan** [comment]
Fantastic, thanks for your contribution to open source, this couldn't be
more helpful right now, this will replace a bunch of nasty ternaries in my
views.
