### ISSUE TITLE
[question] about loadPath, etc.

### ISSUE THREAD

**Issue by trsh** [i18next/i18next-scanner#65]
#### Version
- i18next-scanner: 2.2.1

a) What doe's loadPath actually?
b) How can configure my scan, so the translations are not overwritten on every call?

I mean if I have "slide1maintext": "__STRING_NOT_TRANSLATED__", and I edit it. And run again to add new keys, the translations are gone :/

**Comment by cheton** [comment]
The loadPath is used to keep old translation. You can specify the path relative to current build directory. See examples below:
https://github.com/i18next/i18next-scanner/blob/master/test/transform-stream.js#L245
