### ISSUE TITLE
Support different looking Trans props

### ISSUE THREAD

**Issue by grydstedt** [i18next/i18next-scanner#70]
For parsing the Trans key there are multiple valid ways of doing props:
```
<Trans i18nKey="key" />
<Trans i18nKey='key' />
<Trans i18nKey={"key"} />
<Trans i18nKey={'key'} />
```

Could we add those to the regex?

**Comment by cheton** [comment]
Sure! I will check how to fine tune this part:
```js
const reTrans = new RegExp('<Trans([^]*?)>([^]*?)</\\s*Trans\\s*>', 'gim');
const reTransKey = new RegExp('[^]*i18nKey="([^"]+)"[^]*', 'im');
```

**Comment by grydstedt** [comment]
Awesome. while we're on that another great thing would be the ability to have custom component names and key prop name. We, for example, have a wrapper component that looks like this:

`<I18N __t="key" />`

It would be great if I could custom names in that regex for `Trans` and `i18nKey`

**Comment by wichert** [comment]
FWIW I just submitted PR #71 which changes that code a bit and might make this easier.

**Comment by cheton** [comment]
v2.3.1 added context and count options for Trans
https://github.com/i18next/i18next-scanner/releases/tag/v2.3.1

v2.4.0 added support for using different component name and i18nKey prop:
https://github.com/i18next/i18next-scanner/releases/tag/v2.4.0
```js
trans: {
    component: 'Trans',
    i18nKey: 'i18nKey',
    extensions: ['.js', '.jsx'],
    fallbackKey: true
}
```

**Comment by grydstedt** [comment]
You rock!
