### ISSUE TITLE
Not keeping already written values

### ISSUE THREAD

**Issue by flatoures** [i18next/i18next-scanner#89]
Hi guys,

#### Version
- i18next: <i>11.3.6</i>
- i18next-scanner: <i>2.6.3</i>
- Using gulp execution

#### Configuration
```js
{ // i18next-scanner options
    lngs: ['en', 'fr'],
    defaultLng: 'en',
    sort: true,
    attr: {
        list: ['ng-i18next'],
        extensions: ['.html', '.htm']
    },
    func: {
        list: ['i18next.t', 'i18n.t'],
        extensions: ['.js']
    },
    trans: {
      extensions: [],
    },
    ns: [
      'buttons',
      'errors',
      'export',
      'files',
      'home',
      'modal',
    ],
    defaultValue: '_STRING_NOT_TRANSLATED_',
    resource: {
      loadPath: '{{lng}}/{{ns}}.json',
      savePath: '{{lng}}/{{ns}}.json',
    },
  };
}
```
I have already done some translations but when I relaunch the scanner it will erase all my translation to set them again with the default value.

In the parser.js l.286, is trying to load the resource file but it cannot find it because it is not using the right path.
If I set an absolute path in the config options like below it works fine : 
```json
  loadPath: path.resolve('./src/locales/{{lng}}/{{ns}}.json'),
```
But it sounds strange to have to use absolute path for the loadPath and not for the savePath. Is there something that I am doing wrong to make it work ?

Thanks for you work

**Comment by cheton** [comment]
The loadPath is relative to current working directory, and savePath is relative to the destination path of your gulp task: `gulp.dest('output/path')`

Assume your folder structure looks like below:
```
src/
    app/
        app.js
assets/
    i18n/
        en/
        de/
```

When running Gulp tasks from the parent folder of src, your i18next-scanner task will look like this:

```js
const gulp = require('gulp');
const sort = require('gulp-sort');
const scanner = require('i18next-scanner');

gulp.task('i18next-scanner', function() {
    return gulp.src(['src/**/*.{js,html}'])
        .pipe(sort()) // Sort files in stream by path
        .pipe(scanner({
            lngs: ['en', 'de'], // supported languages
            resource: {
                // the source path is relative to current working directory
                loadPath: 'assets/i18n/{{lng}}/{{ns}}.json',
                
                // the destination path is relative to your `gulp.dest()` path
                savePath: 'i18n/{{lng}}/{{ns}}.json'
            }
        }))
        .pipe(gulp.dest('assets'));
});
```

If you want to prevent loading from the wrong path no matter what directory you run gulp tasks, using absolute path for both loadPath and savePath is the safest way to work around.

**Comment by flatoures** [comment]
Sorry for that, I didn't see these 2 lines of comments. It would have save me some time trying to find out why it didn't load. :(

Thanks for your reply.
