### ISSUE TITLE
React class parse error

### ISSUE THREAD

**Issue by deema089786** [i18next/i18next-scanner#93]
I am using i18next-scanner for get strings from my components. But if I use class field like this

`export default class Main extends Component {`
   `static testvalue = 12;`
   `render(){return(<div><Trans>some string</Trans></div>)}`
`}`

"static testvalue = 12" cause this error

`18next-scanner: Unable to parse Trans component with the content`
`{ SyntaxError: Unexpected token (10:19)`

If I don't use this way for define class fields all works good. How can I fix it?

**Comment by cheton** [comment]
Related to #86

**Comment by saravanan10393** [comment]
@cheton 
This also fails when react class has properties

`
  class Todo extends React.Component{
    todos = [];
    addTodo = (task) => {
       this.todos.push(task)   
    }
  }
`

In my project, i prefer using property function instead of member function to avoid binding to this instance.

Please help.
I am thinking to use React18next for project.

**Comment by LuisSaybe** [comment]
any updates?

**Comment by daliusd** [comment]
Check my answer on https://github.com/i18next/i18next-scanner/issues/88 for some ideas.

**Comment by ctavan** [comment]
@deema089786 can you check if #112 (`npm install @contentpass/i18next-scanner`) fixes the issue for you?

**Comment by ctavan** [comment]
@deema089786 @saravanan10393 @LuisSaybe  can you check if #112 (`npm install @contentpass/i18next-scanner`) fixes the issue for you?

**Comment by ctavan** [comment]
@deema089786 @saravanan10393 @LuisSaybe since my patch has been released, can you check again with `i18next-scanner@2.8.0`?

**Comment by deema089786** [comment]
2.8.0 - all works perfectly. Thanks.
Tested with this code
![image](https://user-images.githubusercontent.com/15146009/49206474-dce10080-f3ba-11e8-8ea6-12421ebd4894.png)
