### ISSUE TITLE
Appending, not replacing the contents of the destination file

### ISSUE THREAD

**Issue by HamidAghdaee** [i18next/i18next-scanner#94]
#### Version
- i18next: <i>11.3.2</i>
- i18next-scanner: <i>2.6.5</i>

#### Configuration
```js
var fs = require("fs");
var chalk = require("chalk");

module.exports = {
  options: {
    debug: true,
    attr: false,
    removeUnusedKeys: true,
    sort: true,
    func: {
      list: ["t"], // 'i18next.t', 'i18n.t',
      extensions: [".tsx"] // '.js', '.jsx',
    },
    trans: false,
    // {
    //     extensions: ['.tsx' ],
    //     fallbackKey: (ns, value) => {
    //         return value;
    //     }
    // },
    lngs: ["en"],
    ns: ["translations", "common", "traffic"],
    defaultNs: "translations",
    defaultValue: null, // '__STRING_NOT_TRANSLATED__',
    resource: {
      loadPath: "locales/{{lng}}/{{ns}}.json",
      savePath: "locales/{{lng}}/{{ns}}.json"
    },
    nsSeparator: ":", // namespace separator
    keySeparator: ".", // key separator
    interpolation: {
      prefix: "{{",
      suffix: "}}"
    }
  },
  transform: function customTransform(file, enc, done) {
    "use strict";
    const parser = this.parser;
    console.log(`Scanning ${file.path}`);
    const content = fs.readFileSync(file.path, enc);
    let count = 0;

    parser.parseFuncFromString(
      content,
      { list: ["i18next._", "i18next.__", "t"] },
      (key, options) => {
        parser.set(
          key,
          Object.assign({}, options, {
            nsSeparator: ":",
            keySeparator: "."
          })
        );
        ++count;
      }
    );

    if (count > 0) {
      console.log(
        `i18next-scanner: count=${chalk.cyan(count)}, file=${chalk.yellow(
          JSON.stringify(file.relative)
        )}`
      );
    }

    done();
  }
};

```
Hi there, 

Thank you for this wonderful library. 

I have the configuration above. The ideal scenario for me would be:

1. The developer inserts call to `i18next.t` in their code with a key `ns:key`, i18next-scanner job is run. 
2. If the job finds the `key` with a non null value in the file `ns`, then it's left alone. If not, its inserted into the file with the value `null`. It is the job of the developer to then provide a value for this key into the translation file. 
3. If the job find any keys not used in source code they're removed from the resource file. (this seems to be done no matter what the value of `removeUnusedKeys`. 

Essentially it seems like i18next-scanner always overrides the translation files with source code. It overwrites whatever is there, I would like it to leave alone any keys for which there are values in the translation file already, add any that are new in source code and remove any that are in translation file and not in source code. 

What's the best way to achieve this with your tool?

Thank you.

-Hamid

**Comment by cheton** [comment]
@HamidAghdaee 

1. You have to disable `removeUnusedKeys` to avoid removing keys no used in source code.

2. Your loadPath may be incorrect so it always overrides existing translation files. See https://github.com/i18next/i18next-scanner/issues/89#issuecomment-406119305

    ```js
    resource: {
        // the load path is relative to current working directory
        loadPath: 'assets/i18n/{{lng}}/{{ns}}.json',

        // the save path is relative to the output path
        savePath: 'i18n/{{lng}}/{{ns}}.json'
    }
    ```

    You can try using absolute path to mitigate this issue:

    ```js
    path.resolve('./locales/{{lng}}/{{ns}}.json')
    ```

**Comment by HamidAghdaee** [comment]
Thank you. That answers my question

**Comment by LinAlSara** [comment]
In my case, overriding existing translation files occurred due to invalid json (extra commas) in the translation files
